apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmail-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path