// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntEmailsColumns holds the columns for the "ent_emails" table.
	EntEmailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "from", Type: field.TypeString},
		{Name: "to", Type: field.TypeJSON},
		{Name: "date", Type: field.TypeString},
		{Name: "topic", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
	}
	// EntEmailsTable holds the schema information for the "ent_emails" table.
	EntEmailsTable = &schema.Table{
		Name:       "ent_emails",
		Columns:    EntEmailsColumns,
		PrimaryKey: []*schema.Column{EntEmailsColumns[0]},
	}
	// EntTemporaryEmailsColumns holds the columns for the "ent_temporary_emails" table.
	EntTemporaryEmailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString},
		{Name: "ent_user_owns", Type: field.TypeInt, Nullable: true},
	}
	// EntTemporaryEmailsTable holds the schema information for the "ent_temporary_emails" table.
	EntTemporaryEmailsTable = &schema.Table{
		Name:       "ent_temporary_emails",
		Columns:    EntTemporaryEmailsColumns,
		PrimaryKey: []*schema.Column{EntTemporaryEmailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ent_temporary_emails_ent_users_owns",
				Columns:    []*schema.Column{EntTemporaryEmailsColumns[2]},
				RefColumns: []*schema.Column{EntUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EntUsersColumns holds the columns for the "ent_users" table.
	EntUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account", Type: field.TypeString},
	}
	// EntUsersTable holds the schema information for the "ent_users" table.
	EntUsersTable = &schema.Table{
		Name:       "ent_users",
		Columns:    EntUsersColumns,
		PrimaryKey: []*schema.Column{EntUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntEmailsTable,
		EntTemporaryEmailsTable,
		EntUsersTable,
	}
)

func init() {
	EntTemporaryEmailsTable.ForeignKeys[0].RefTable = EntUsersTable
}
