// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"helix.io/helix/ent/entemail"
	"helix.io/helix/ent/predicate"
)

// EntEmailQuery is the builder for querying EntEmail entities.
type EntEmailQuery struct {
	config
	ctx        *QueryContext
	order      []entemail.OrderOption
	inters     []Interceptor
	predicates []predicate.EntEmail
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EntEmail) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntEmailQuery builder.
func (eeq *EntEmailQuery) Where(ps ...predicate.EntEmail) *EntEmailQuery {
	eeq.predicates = append(eeq.predicates, ps...)
	return eeq
}

// Limit the number of records to be returned by this query.
func (eeq *EntEmailQuery) Limit(limit int) *EntEmailQuery {
	eeq.ctx.Limit = &limit
	return eeq
}

// Offset to start from.
func (eeq *EntEmailQuery) Offset(offset int) *EntEmailQuery {
	eeq.ctx.Offset = &offset
	return eeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eeq *EntEmailQuery) Unique(unique bool) *EntEmailQuery {
	eeq.ctx.Unique = &unique
	return eeq
}

// Order specifies how the records should be ordered.
func (eeq *EntEmailQuery) Order(o ...entemail.OrderOption) *EntEmailQuery {
	eeq.order = append(eeq.order, o...)
	return eeq
}

// First returns the first EntEmail entity from the query.
// Returns a *NotFoundError when no EntEmail was found.
func (eeq *EntEmailQuery) First(ctx context.Context) (*EntEmail, error) {
	nodes, err := eeq.Limit(1).All(setContextOp(ctx, eeq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entemail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eeq *EntEmailQuery) FirstX(ctx context.Context) *EntEmail {
	node, err := eeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntEmail ID from the query.
// Returns a *NotFoundError when no EntEmail ID was found.
func (eeq *EntEmailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eeq.Limit(1).IDs(setContextOp(ctx, eeq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entemail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eeq *EntEmailQuery) FirstIDX(ctx context.Context) int {
	id, err := eeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntEmail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntEmail entity is found.
// Returns a *NotFoundError when no EntEmail entities are found.
func (eeq *EntEmailQuery) Only(ctx context.Context) (*EntEmail, error) {
	nodes, err := eeq.Limit(2).All(setContextOp(ctx, eeq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entemail.Label}
	default:
		return nil, &NotSingularError{entemail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eeq *EntEmailQuery) OnlyX(ctx context.Context) *EntEmail {
	node, err := eeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntEmail ID in the query.
// Returns a *NotSingularError when more than one EntEmail ID is found.
// Returns a *NotFoundError when no entities are found.
func (eeq *EntEmailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eeq.Limit(2).IDs(setContextOp(ctx, eeq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entemail.Label}
	default:
		err = &NotSingularError{entemail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eeq *EntEmailQuery) OnlyIDX(ctx context.Context) int {
	id, err := eeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntEmails.
func (eeq *EntEmailQuery) All(ctx context.Context) ([]*EntEmail, error) {
	ctx = setContextOp(ctx, eeq.ctx, ent.OpQueryAll)
	if err := eeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntEmail, *EntEmailQuery]()
	return withInterceptors[[]*EntEmail](ctx, eeq, qr, eeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eeq *EntEmailQuery) AllX(ctx context.Context) []*EntEmail {
	nodes, err := eeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntEmail IDs.
func (eeq *EntEmailQuery) IDs(ctx context.Context) (ids []int, err error) {
	if eeq.ctx.Unique == nil && eeq.path != nil {
		eeq.Unique(true)
	}
	ctx = setContextOp(ctx, eeq.ctx, ent.OpQueryIDs)
	if err = eeq.Select(entemail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eeq *EntEmailQuery) IDsX(ctx context.Context) []int {
	ids, err := eeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eeq *EntEmailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eeq.ctx, ent.OpQueryCount)
	if err := eeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eeq, querierCount[*EntEmailQuery](), eeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eeq *EntEmailQuery) CountX(ctx context.Context) int {
	count, err := eeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eeq *EntEmailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eeq.ctx, ent.OpQueryExist)
	switch _, err := eeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eeq *EntEmailQuery) ExistX(ctx context.Context) bool {
	exist, err := eeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntEmailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eeq *EntEmailQuery) Clone() *EntEmailQuery {
	if eeq == nil {
		return nil
	}
	return &EntEmailQuery{
		config:     eeq.config,
		ctx:        eeq.ctx.Clone(),
		order:      append([]entemail.OrderOption{}, eeq.order...),
		inters:     append([]Interceptor{}, eeq.inters...),
		predicates: append([]predicate.EntEmail{}, eeq.predicates...),
		// clone intermediate query.
		sql:  eeq.sql.Clone(),
		path: eeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		From string `json:"from,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntEmail.Query().
//		GroupBy(entemail.FieldFrom).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eeq *EntEmailQuery) GroupBy(field string, fields ...string) *EntEmailGroupBy {
	eeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntEmailGroupBy{build: eeq}
	grbuild.flds = &eeq.ctx.Fields
	grbuild.label = entemail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		From string `json:"from,omitempty"`
//	}
//
//	client.EntEmail.Query().
//		Select(entemail.FieldFrom).
//		Scan(ctx, &v)
func (eeq *EntEmailQuery) Select(fields ...string) *EntEmailSelect {
	eeq.ctx.Fields = append(eeq.ctx.Fields, fields...)
	sbuild := &EntEmailSelect{EntEmailQuery: eeq}
	sbuild.label = entemail.Label
	sbuild.flds, sbuild.scan = &eeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntEmailSelect configured with the given aggregations.
func (eeq *EntEmailQuery) Aggregate(fns ...AggregateFunc) *EntEmailSelect {
	return eeq.Select().Aggregate(fns...)
}

func (eeq *EntEmailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eeq); err != nil {
				return err
			}
		}
	}
	for _, f := range eeq.ctx.Fields {
		if !entemail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eeq.path != nil {
		prev, err := eeq.path(ctx)
		if err != nil {
			return err
		}
		eeq.sql = prev
	}
	return nil
}

func (eeq *EntEmailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntEmail, error) {
	var (
		nodes = []*EntEmail{}
		_spec = eeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntEmail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntEmail{config: eeq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(eeq.modifiers) > 0 {
		_spec.Modifiers = eeq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range eeq.loadTotal {
		if err := eeq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eeq *EntEmailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eeq.querySpec()
	if len(eeq.modifiers) > 0 {
		_spec.Modifiers = eeq.modifiers
	}
	_spec.Node.Columns = eeq.ctx.Fields
	if len(eeq.ctx.Fields) > 0 {
		_spec.Unique = eeq.ctx.Unique != nil && *eeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eeq.driver, _spec)
}

func (eeq *EntEmailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entemail.Table, entemail.Columns, sqlgraph.NewFieldSpec(entemail.FieldID, field.TypeInt))
	_spec.From = eeq.sql
	if unique := eeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eeq.path != nil {
		_spec.Unique = true
	}
	if fields := eeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entemail.FieldID)
		for i := range fields {
			if fields[i] != entemail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eeq *EntEmailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eeq.driver.Dialect())
	t1 := builder.Table(entemail.Table)
	columns := eeq.ctx.Fields
	if len(columns) == 0 {
		columns = entemail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eeq.sql != nil {
		selector = eeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eeq.ctx.Unique != nil && *eeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eeq.predicates {
		p(selector)
	}
	for _, p := range eeq.order {
		p(selector)
	}
	if offset := eeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntEmailGroupBy is the group-by builder for EntEmail entities.
type EntEmailGroupBy struct {
	selector
	build *EntEmailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eegb *EntEmailGroupBy) Aggregate(fns ...AggregateFunc) *EntEmailGroupBy {
	eegb.fns = append(eegb.fns, fns...)
	return eegb
}

// Scan applies the selector query and scans the result into the given value.
func (eegb *EntEmailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eegb.build.ctx, ent.OpQueryGroupBy)
	if err := eegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntEmailQuery, *EntEmailGroupBy](ctx, eegb.build, eegb, eegb.build.inters, v)
}

func (eegb *EntEmailGroupBy) sqlScan(ctx context.Context, root *EntEmailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eegb.fns))
	for _, fn := range eegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eegb.flds)+len(eegb.fns))
		for _, f := range *eegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntEmailSelect is the builder for selecting fields of EntEmail entities.
type EntEmailSelect struct {
	*EntEmailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ees *EntEmailSelect) Aggregate(fns ...AggregateFunc) *EntEmailSelect {
	ees.fns = append(ees.fns, fns...)
	return ees
}

// Scan applies the selector query and scans the result into the given value.
func (ees *EntEmailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ees.ctx, ent.OpQuerySelect)
	if err := ees.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntEmailQuery, *EntEmailSelect](ctx, ees.EntEmailQuery, ees, ees.inters, v)
}

func (ees *EntEmailSelect) sqlScan(ctx context.Context, root *EntEmailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ees.fns))
	for _, fn := range ees.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ees.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ees.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
