// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"helix.io/helix/ent/enttemporaryemail"
	"helix.io/helix/ent/entuser"
	"helix.io/helix/ent/predicate"
)

// EntUserQuery is the builder for querying EntUser entities.
type EntUserQuery struct {
	config
	ctx           *QueryContext
	order         []entuser.OrderOption
	inters        []Interceptor
	predicates    []predicate.EntUser
	withOwns      *EntTemporaryEmailQuery
	modifiers     []func(*sql.Selector)
	loadTotal     []func(context.Context, []*EntUser) error
	withNamedOwns map[string]*EntTemporaryEmailQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntUserQuery builder.
func (euq *EntUserQuery) Where(ps ...predicate.EntUser) *EntUserQuery {
	euq.predicates = append(euq.predicates, ps...)
	return euq
}

// Limit the number of records to be returned by this query.
func (euq *EntUserQuery) Limit(limit int) *EntUserQuery {
	euq.ctx.Limit = &limit
	return euq
}

// Offset to start from.
func (euq *EntUserQuery) Offset(offset int) *EntUserQuery {
	euq.ctx.Offset = &offset
	return euq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (euq *EntUserQuery) Unique(unique bool) *EntUserQuery {
	euq.ctx.Unique = &unique
	return euq
}

// Order specifies how the records should be ordered.
func (euq *EntUserQuery) Order(o ...entuser.OrderOption) *EntUserQuery {
	euq.order = append(euq.order, o...)
	return euq
}

// QueryOwns chains the current query on the "owns" edge.
func (euq *EntUserQuery) QueryOwns() *EntTemporaryEmailQuery {
	query := (&EntTemporaryEmailClient{config: euq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := euq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := euq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entuser.Table, entuser.FieldID, selector),
			sqlgraph.To(enttemporaryemail.Table, enttemporaryemail.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, entuser.OwnsTable, entuser.OwnsColumn),
		)
		fromU = sqlgraph.SetNeighbors(euq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EntUser entity from the query.
// Returns a *NotFoundError when no EntUser was found.
func (euq *EntUserQuery) First(ctx context.Context) (*EntUser, error) {
	nodes, err := euq.Limit(1).All(setContextOp(ctx, euq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (euq *EntUserQuery) FirstX(ctx context.Context) *EntUser {
	node, err := euq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntUser ID from the query.
// Returns a *NotFoundError when no EntUser ID was found.
func (euq *EntUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = euq.Limit(1).IDs(setContextOp(ctx, euq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (euq *EntUserQuery) FirstIDX(ctx context.Context) int {
	id, err := euq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntUser entity is found.
// Returns a *NotFoundError when no EntUser entities are found.
func (euq *EntUserQuery) Only(ctx context.Context) (*EntUser, error) {
	nodes, err := euq.Limit(2).All(setContextOp(ctx, euq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entuser.Label}
	default:
		return nil, &NotSingularError{entuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (euq *EntUserQuery) OnlyX(ctx context.Context) *EntUser {
	node, err := euq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntUser ID in the query.
// Returns a *NotSingularError when more than one EntUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (euq *EntUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = euq.Limit(2).IDs(setContextOp(ctx, euq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entuser.Label}
	default:
		err = &NotSingularError{entuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (euq *EntUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := euq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntUsers.
func (euq *EntUserQuery) All(ctx context.Context) ([]*EntUser, error) {
	ctx = setContextOp(ctx, euq.ctx, ent.OpQueryAll)
	if err := euq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntUser, *EntUserQuery]()
	return withInterceptors[[]*EntUser](ctx, euq, qr, euq.inters)
}

// AllX is like All, but panics if an error occurs.
func (euq *EntUserQuery) AllX(ctx context.Context) []*EntUser {
	nodes, err := euq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntUser IDs.
func (euq *EntUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if euq.ctx.Unique == nil && euq.path != nil {
		euq.Unique(true)
	}
	ctx = setContextOp(ctx, euq.ctx, ent.OpQueryIDs)
	if err = euq.Select(entuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (euq *EntUserQuery) IDsX(ctx context.Context) []int {
	ids, err := euq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (euq *EntUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, euq.ctx, ent.OpQueryCount)
	if err := euq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, euq, querierCount[*EntUserQuery](), euq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (euq *EntUserQuery) CountX(ctx context.Context) int {
	count, err := euq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (euq *EntUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, euq.ctx, ent.OpQueryExist)
	switch _, err := euq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (euq *EntUserQuery) ExistX(ctx context.Context) bool {
	exist, err := euq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (euq *EntUserQuery) Clone() *EntUserQuery {
	if euq == nil {
		return nil
	}
	return &EntUserQuery{
		config:     euq.config,
		ctx:        euq.ctx.Clone(),
		order:      append([]entuser.OrderOption{}, euq.order...),
		inters:     append([]Interceptor{}, euq.inters...),
		predicates: append([]predicate.EntUser{}, euq.predicates...),
		withOwns:   euq.withOwns.Clone(),
		// clone intermediate query.
		sql:  euq.sql.Clone(),
		path: euq.path,
	}
}

// WithOwns tells the query-builder to eager-load the nodes that are connected to
// the "owns" edge. The optional arguments are used to configure the query builder of the edge.
func (euq *EntUserQuery) WithOwns(opts ...func(*EntTemporaryEmailQuery)) *EntUserQuery {
	query := (&EntTemporaryEmailClient{config: euq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	euq.withOwns = query
	return euq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Account string `json:"account,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntUser.Query().
//		GroupBy(entuser.FieldAccount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (euq *EntUserQuery) GroupBy(field string, fields ...string) *EntUserGroupBy {
	euq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntUserGroupBy{build: euq}
	grbuild.flds = &euq.ctx.Fields
	grbuild.label = entuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Account string `json:"account,omitempty"`
//	}
//
//	client.EntUser.Query().
//		Select(entuser.FieldAccount).
//		Scan(ctx, &v)
func (euq *EntUserQuery) Select(fields ...string) *EntUserSelect {
	euq.ctx.Fields = append(euq.ctx.Fields, fields...)
	sbuild := &EntUserSelect{EntUserQuery: euq}
	sbuild.label = entuser.Label
	sbuild.flds, sbuild.scan = &euq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntUserSelect configured with the given aggregations.
func (euq *EntUserQuery) Aggregate(fns ...AggregateFunc) *EntUserSelect {
	return euq.Select().Aggregate(fns...)
}

func (euq *EntUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range euq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, euq); err != nil {
				return err
			}
		}
	}
	for _, f := range euq.ctx.Fields {
		if !entuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if euq.path != nil {
		prev, err := euq.path(ctx)
		if err != nil {
			return err
		}
		euq.sql = prev
	}
	return nil
}

func (euq *EntUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntUser, error) {
	var (
		nodes       = []*EntUser{}
		_spec       = euq.querySpec()
		loadedTypes = [1]bool{
			euq.withOwns != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntUser{config: euq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(euq.modifiers) > 0 {
		_spec.Modifiers = euq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, euq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := euq.withOwns; query != nil {
		if err := euq.loadOwns(ctx, query, nodes,
			func(n *EntUser) { n.Edges.Owns = []*EntTemporaryEmail{} },
			func(n *EntUser, e *EntTemporaryEmail) { n.Edges.Owns = append(n.Edges.Owns, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range euq.withNamedOwns {
		if err := euq.loadOwns(ctx, query, nodes,
			func(n *EntUser) { n.appendNamedOwns(name) },
			func(n *EntUser, e *EntTemporaryEmail) { n.appendNamedOwns(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range euq.loadTotal {
		if err := euq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (euq *EntUserQuery) loadOwns(ctx context.Context, query *EntTemporaryEmailQuery, nodes []*EntUser, init func(*EntUser), assign func(*EntUser, *EntTemporaryEmail)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*EntUser)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.EntTemporaryEmail(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(entuser.OwnsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ent_user_owns
		if fk == nil {
			return fmt.Errorf(`foreign-key "ent_user_owns" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ent_user_owns" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (euq *EntUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := euq.querySpec()
	if len(euq.modifiers) > 0 {
		_spec.Modifiers = euq.modifiers
	}
	_spec.Node.Columns = euq.ctx.Fields
	if len(euq.ctx.Fields) > 0 {
		_spec.Unique = euq.ctx.Unique != nil && *euq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, euq.driver, _spec)
}

func (euq *EntUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entuser.Table, entuser.Columns, sqlgraph.NewFieldSpec(entuser.FieldID, field.TypeInt))
	_spec.From = euq.sql
	if unique := euq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if euq.path != nil {
		_spec.Unique = true
	}
	if fields := euq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entuser.FieldID)
		for i := range fields {
			if fields[i] != entuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := euq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := euq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := euq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := euq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (euq *EntUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(euq.driver.Dialect())
	t1 := builder.Table(entuser.Table)
	columns := euq.ctx.Fields
	if len(columns) == 0 {
		columns = entuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if euq.sql != nil {
		selector = euq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if euq.ctx.Unique != nil && *euq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range euq.predicates {
		p(selector)
	}
	for _, p := range euq.order {
		p(selector)
	}
	if offset := euq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := euq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedOwns tells the query-builder to eager-load the nodes that are connected to the "owns"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (euq *EntUserQuery) WithNamedOwns(name string, opts ...func(*EntTemporaryEmailQuery)) *EntUserQuery {
	query := (&EntTemporaryEmailClient{config: euq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if euq.withNamedOwns == nil {
		euq.withNamedOwns = make(map[string]*EntTemporaryEmailQuery)
	}
	euq.withNamedOwns[name] = query
	return euq
}

// EntUserGroupBy is the group-by builder for EntUser entities.
type EntUserGroupBy struct {
	selector
	build *EntUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eugb *EntUserGroupBy) Aggregate(fns ...AggregateFunc) *EntUserGroupBy {
	eugb.fns = append(eugb.fns, fns...)
	return eugb
}

// Scan applies the selector query and scans the result into the given value.
func (eugb *EntUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eugb.build.ctx, ent.OpQueryGroupBy)
	if err := eugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntUserQuery, *EntUserGroupBy](ctx, eugb.build, eugb, eugb.build.inters, v)
}

func (eugb *EntUserGroupBy) sqlScan(ctx context.Context, root *EntUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eugb.fns))
	for _, fn := range eugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eugb.flds)+len(eugb.fns))
		for _, f := range *eugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntUserSelect is the builder for selecting fields of EntUser entities.
type EntUserSelect struct {
	*EntUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eus *EntUserSelect) Aggregate(fns ...AggregateFunc) *EntUserSelect {
	eus.fns = append(eus.fns, fns...)
	return eus
}

// Scan applies the selector query and scans the result into the given value.
func (eus *EntUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eus.ctx, ent.OpQuerySelect)
	if err := eus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntUserQuery, *EntUserSelect](ctx, eus.EntUserQuery, eus, eus.inters, v)
}

func (eus *EntUserSelect) sqlScan(ctx context.Context, root *EntUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eus.fns))
	for _, fn := range eus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
