// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (ete *EntTemporaryEmail) Owner(ctx context.Context) (*EntUser, error) {
	result, err := ete.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = ete.QueryOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (eu *EntUser) Owns(ctx context.Context) (result []*EntTemporaryEmail, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = eu.NamedOwns(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = eu.Edges.OwnsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = eu.QueryOwns().All(ctx)
	}
	return result, err
}
