// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EntEmail is the predicate function for entemail builders.
type EntEmail func(*sql.Selector)

// EntTemporaryEmail is the predicate function for enttemporaryemail builders.
type EntTemporaryEmail func(*sql.Selector)

// EntUser is the predicate function for entuser builders.
type EntUser func(*sql.Selector)
